// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.4_eslint@8.51.0_rollup@3.29.4_sass@1.69.2_typescript@5.2.2_vite@4.5.0_vue-tsc@1.8.19/node_modules/nuxt/dist/app/plugins/revive-payload.server").default> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.4_eslint@8.51.0_rollup@3.29.4_sass@1.69.2_typescript@5.2.2_vite@4.5.0_vue-tsc@1.8.19/node_modules/nuxt/dist/app/plugins/revive-payload.client").default> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.4_eslint@8.51.0_rollup@3.29.4_sass@1.69.2_typescript@5.2.2_vite@4.5.0_vue-tsc@1.8.19/node_modules/nuxt/dist/head/runtime/plugins/unhead").default> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.4_eslint@8.51.0_rollup@3.29.4_sass@1.69.2_typescript@5.2.2_vite@4.5.0_vue-tsc@1.8.19/node_modules/nuxt/dist/app/plugins/router").default> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.4_eslint@8.51.0_rollup@3.29.4_sass@1.69.2_typescript@5.2.2_vite@4.5.0_vue-tsc@1.8.19/node_modules/nuxt/dist/app/plugins/chunk-reload.client").default> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@3.8.1_@types+node@20.8.4_eslint@8.51.0_rollup@3.29.4_sass@1.69.2_typescript@5.2.2_vite@4.5.0_vue-tsc@1.8.19/node_modules/nuxt/dist/app/plugins/check-outdated-build.client").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
